### ISSUE TITLE
Code Organization for Engine module

### ISSUE THREAD

**Issue by whitef0x0** [IMacMcGraw/Necromunda#4]
After reading this http://read.humanjavascript.com/ch04-organizing-your-code.html, seems like the most elegant solution to our organization of our engine object would be to use [commonJS] (http://commonjs.org/), and use patterns mentioned in [this blog post](http://read.humanjavascript.com/ch04-organizing-your-code.html).

**Comment by IMacMcGraw** [comment]
I'll take a look!
